<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Ejercicio3 Ismael</title>
</head>

<body>
    <?php

    use PhpOffice\PhpWord\Shared\Converter;

    $curriculum = array(
        'Nombre' => 'Ismael Flores Sánchez', 'Datos Personales' => 'Calle Amapola Nº17Garrucha 04630 · (+34)663867369 · ismaelfloressanchez@gmail.com · Fecha de nacimiento: 01/06/2001',
        'Un Poco Sobre Mi' => 'Ahora mismo soy un desarroyador web en potencia, me queda meses para terminar el ciclo superior de desarroyador de aplicaciones web',
        'Experiencia_1' => 'Monitor · Niños Pre benjamín · CAMPUS CD GARRUCHA BASKET', 'Experiencia_2' => 'Practicas del Curso SMR · Garrucha Almeria · InformáticaCerda',
        'Educacion_1' => 'I.E.S Mediterráneo · Garrucha,Almeria · ESO', 'Educacion_2' => 'I.E.S Cura Valera · Huercal Overa, Almería · Ciclo Medio de Informática: Sistemas Microinformáticosy Redes',
        'Educacion_3' => 'Pabellón Vista Alegre · Garrucha, Almería · Curso de entrenador de baloncesto:Nivel 0', 'Educacion_4' => 'I.E.S Jaroso · Cuevas de Almanzora, Almería · Ciclo Superior de Programación: Desarrollo de Aplicaciones Web Terminandolo voy por el segundo año',
        'Interes' => 'Apart from being a web developer, I enjoy most of my time being outdoors. In the winter, I am an avid skier and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing, and kayaking.'
    );


    $vendorDirPath = realpath(__DIR__ . '/vendor');
    if (file_exists($vendorDirPath . '/autoload.php')) {
        require $vendorDirPath . '/autoload.php';
    } else {
        throw new Exception(
            sprintf(
                'Could not find file \'%s\'. It is generated by Composer. Use \'install --prefer-source\' or \'update --prefer-source\' Composer commands to move forward.',
                $vendorDirPath . '/autoload.php'
            )
        );
    }

    // Creating the new document...
    $phpWord = new \PhpOffice\PhpWord\PhpWord();

    /* Note: any element you append to a document must reside inside of a Section. */

    // Adding an empty Section to the document...
    $section = $phpWord->addSection();

    $subsequent = $section->addHeader();
    $subsequent->addText('Ismael Flores Sánchez ');

    //Absolute positioning
    $section->addImage(
        'img/imagen1.png',
        array(
            'width'            => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(3),
            'height'           => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(3),
            'marginRight'       => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(15.5),
            'marginTop'        => \PhpOffice\PhpWord\Shared\Converter::cmToPixel(5),
            'positioning'      => \PhpOffice\PhpWord\Style\Image::POSITION_ABSOLUTE,
            'posHorizontal'    => \PhpOffice\PhpWord\Style\Image::POSITION_HORIZONTAL_RIGHT,
            'posHorizontalRel' => \PhpOffice\PhpWord\Style\Image::POSITION_RELATIVE_TO_PAGE,
            'posVerticalRel'   => \PhpOffice\PhpWord\Style\Image::POSITION_RELATIVE_TO_PAGE,
            'borderBottomColor' => "black",
        )
    );


    foreach ($curriculum as $key => $value) {
        // Adding Text element with font customized inline...
        $section->addText(
            $key,
            array('name' => 'Tahoma', 'size' => 18, 'color' => 'AABBFF', 'bold' => true)
        );
        $section->addText(
            $value,
            array('name' => 'Tahoma', 'size' => 12,)
        );
    }


    // Saving the document as OOXML file...
    $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
    $objWriter->save('curriculumIsmael.docx');
    ?>
</body>

</html>